oat-sa/tao-item-runner-qti-fe

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/AssociateInteraction.js
Jira: https://oat-sa.atlassian.net/browse/TAO-7920
- we should remove the deactivated status only if the maxAssociations are set higher than 0
- version bump
Post-merge:
=> fix for associate choice limitation

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/AssociateInteraction.js
Related to: https://oat-sa.atlassian.net/browse/TAO-8952
Forward port of a hotfix made in https://github.com/oat-sa/extension-tao-itemqti/pull/1322
Allows to drag and scroll on the associate interaction.
Once merged, don't forget to release and publish into npm.
=> Fix/tao 8952/drag and scroll associate interaction

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/AssociateInteraction.js
- [Fix] [TAO-8952](https://oat-sa.atlassian.net/browse/TAO-8952) Add drag and scroll on the associate interaction [#14](https://github.com/oat-sa/tao-item-runner-qti-fe/pull/14)
=> Release 0.4.2

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/AssociateInteraction.js
Conflict between draggable element and drag zone events fixed
=> Release 0.4.3

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/GapMatchInteraction.js
Jira: https://oat-sa.atlassian.net/browse/TAO-8988
- this modification allows the choice to be dragged outside of its container
(https://interactjs.io/docs/restriction)
Post-merge:
=> fix left side limitation

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/GapMatchInteraction.js
**Backport**
- [Fix] [TAO-8988](https://oat-sa.atlassian.net/browse/TAO-8988) Fix left side limitation [#18](https://github.com/oat-sa/tao-item-runner-qti-fe/pull/18)
=> Hotfix/tao 8999/fix interaction drop on left

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/GraphicOrderInteraction.js
Version 0.4.5
- [Fix] [TAO-9085](https://oat-sa.atlassian.net/browse/TAO-9085) minChoices and maxChoices can be equal to the size of choices [#22](https://github.com/oat-sa/tao-item-runner-qti-fe/pull/22)
=> Release 0.4.5

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/GraphicAssociateInteraction.js
Version 0.4.6
- [Fix] [TAO-9084](https://oat-sa.atlassian.net/browse/TAO-9084) GraphicOrderInteraction prevent duplicated associations [#24](https://github.com/oat-sa/oat-sa/tao-item-runner-qti-fe/pull/24)
=> Release 0.4.6

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/GraphicGapMatchInteraction.js
**Related to task:** 
https://oat-sa.atlassian.net/browse/NEC-28
drag’n drop graphics don't work
**Depends:**
https://github.com/oat-sa/extension-tao-itemqti/pull/1352
=> Fix/nec 28/graphic interaction drag and drop

package.json, src/runner/provider/qti.js
Version 0.4.7
- [Fix] [SI-351](https://oat-sa.atlassian.net/browse/SI-351) Trigger a new event if post rendering error [#11](https://github.com/oat-sa/<REPO>/pull/11)
=> Release 0.4.7

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/GapMatchInteraction.js
**Related to task:** 
https://oat-sa.atlassian.net/browse/NEC-30
System throws error `TypeError: Cannot read property 'attr' of null`
1. Go to item;
2. Answer it;
3. Go to next Item;
4. Go to previous ( to get to the item again);
5. Check if is there any error.
=> Fix/nec 30/gap match interaction reload

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/GapMatchInteraction.js
Version 0.4.9
- [Fix] [NEC-30](https://oat-sa.atlassian.net/browse/NEC-30) Fix gap match interaction reload [#29](https://github.com/oat-sa/tao-item-runner-qti-fe/pull/29)
=> Release 0.4.9

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ChoiceInteraction.js, src/qtiCommonRenderer/renderers/interactions/GapMatchInteraction.js, src/qtiCommonRenderer/renderers/interactions/GraphicGapMatchInteraction.js, src/qtiCommonRenderer/renderers/interactions/MatchInteraction.js, src/qtiCommonRenderer/renderers/interactions/OrderInteraction.js
Version 0.4.10
- [Fix] [NEC-31](https://oat-sa.atlassian.net/browse/NEC-31) Escape data-identifier attribute selectors [#31](https://github.com/oat-sa/tao-item-runner-qti-fe/pull/31)
=> Release 0.4.10

package-lock.json, package.json, src/qtiCommonRenderer/helpers/itemStylesheetHandler.js
=> Release 0.4.14

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/SliderInteraction.js
Version 0.4.15
Release notes :
[fix] [UDIR-31](https://oat-sa.atlassian.net/browse/UDI-31)
Fixed a weird behaviour of a Slider interaction in authoring when manipulating with adding and removing it several times for one item. 
PR #48
=> Release 0.4.15

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js, src/qtiCommonRenderer/tpl/interactions/extendedTextInteraction.tpl
**Related to**
https://oat-sa.atlassian.net/browse/BOSA-32
**Part of**
https://github.com/oat-sa/extension-tao-itemqti/pull/1393
**How to test**
- Steps to validate in Authoring
- Extended text
- Create a new ExtendedText interaction, change constraints to Max Length or Max Words makes appear the text 0 of x (chars/words) maximum
- Putting the constraint to none remove the text
- Editing a new or imported or saved ExtendedText interaction, when you change the value of constraints Max Length or Max words, the component in real-time change it text (0 of x (chars/words) maximum)
- Steps to validate in Preview of backoffice
- Text entry
- Validate that the Max Length or Max Words constraints works
- Extended text
- Validate that the Max Length or Max Words constraints works
- See if the text …
=> Max length count

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js, src/qtiCommonRenderer/tpl/interactions/extendedTextInteraction.tpl
=> Release 0.4.17

package-lock.json, package.json, src/qtiCommonRenderer/helpers/uploadMime.js
=> Release 0.4.18

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/TextEntryInteraction.js
=> Release 0.4.19

.gitignore, package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/TextEntryInteraction.js, test/qtiCommonRenderer/interactions/textEntry/test.js
=> Release 0.4.20

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
=> Release 0.4.21

.eslintrc.json, package-lock.json, package.json, src/qtiCommonRenderer/helpers/container.js, test/qtiCommonRenderer/helpers/container/test.html, test/qtiCommonRenderer/helpers/container/test.js
=> Release 0.5.0

package-lock.json, package.json, src/qtiCommonRenderer/tpl/img.tpl
=> Release 0.6.1

package-lock.json, package.json, src/reviewRenderer/renderers/config.js, src/reviewRenderer/renderers/interactions/MediaInteraction.js
=> Release 0.7.0

package-lock.json, package.json
Related to https://github.com/oat-sa/tao-item-runner-qti-fe/pull/73
=> Update version in package.json

package-lock.json, package.json, src/qtiCommonRenderer/tpl/img.tpl
Related to : https://oat-sa.atlassian.net/browse/TCA-638
Apply aria attributes to images
- prepare an instance of TAO
- import test assigned to https://oat-sa.atlassian.net/browse/TCA-604
- executed delivery created from test as a test taker
- make sure that aria attributes are in place
Companion PR :
=> Release 0.9.0

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
=> Release 0.10.0

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
**Related to**
https://oat-sa.atlassian.net/browse/BSA-183
This PR is for avoid overwrite ckeditor configs relative to translations to put only in one place
=> Fix BSA 183 - Avoid overwrite ckeditor configs for properly translations

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
=> Release 0.10.1

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/TextEntryInteraction.js
**Fix comments of this PR**
https://github.com/oat-sa/tao-item-runner-qti-fe/pull/96
=> Fix code style and other comments in old PR

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/TextEntryInteraction.js
=> Release 0.11.1

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ChoiceInteraction.js
Version 0.11.2
- [feature] [TCA-765](https://oat-sa.atlassian.net/browse/TCA-765)
focus choice interaction on mouse click
https://github.com/oat-sa/tao-item-runner-qti-fe/pull/103
=> Release 0.11.2

package-lock.json, package.json, src/qtiCommonRenderer/tpl/img.tpl
=> Release 0.13.1

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js, src/reviewRenderer/renderers/interactions/ExtendedTextInteraction.js, test/qtiCommonRenderer/interactions/extendedText/test.js, test/reviewRenderer/interactions/extendedText/test.js
=> Release 0.14.1

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/MediaInteraction.js
=> Release 0.15.1

package-lock.json, package.json, src/reviewRenderer/renderers/interactions/TextEntryInteraction.js, src/reviewRenderer/tpl/interactions/textEntryInteraction.tpl, test/reviewRenderer/interactions/textEntry/test.html, test/reviewRenderer/interactions/textEntry/test.js
=> Release 0.15.5

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
=> Release 0.15.6

package-lock.json, package.json, src/reviewRenderer/renderers/interactions/TextEntryInteraction.js, src/reviewRenderer/tpl/interactions/textEntryInteraction.tpl, test/reviewRenderer/interactions/textEntry/test.js
Ticket: https://oat-sa.atlassian.net/browse/MS-772
- DOM structure of the inline text entry interaction to support the new design
Related PR: https://github.com/oat-sa/extension-tao-itemqti/pull/1609
=> Feature/ms 772/prevent scrolling text entry

package-lock.json, package.json, src/reviewRenderer/renderers/interactions/TextEntryInteraction.js, src/reviewRenderer/tpl/interactions/textEntryInteraction.tpl, test/reviewRenderer/interactions/textEntry/test.js
=> Release 0.16.0

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/MediaInteraction.js
Related to: https://oat-sa.atlassian.net/browse/CON-30
https://github.com/oat-sa/tao-core/pull/2780
https://github.com/oat-sa/tao-core-ui-fe/pull/243
https://github.com/oat-sa/extension-tao-mediamanager/pull/248
https://github.com/oat-sa/extension-tao-test-preview-ui-loader/pull/17
https://github.com/oat-sa/extension-tao-itemqti/pull/1610
Support video responsive width in Media Interaction.
How to test:
- go to Items Authoring
- add video by Media Interaction
- try to scale
- check scale in preview
=> Feature/CON-30/support responsive video in Media Interaction

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/MediaInteraction.js
=> Release 0.17.0

package-lock.json, package.json, src/reviewRenderer/renderers/interactions/ExtendedTextInteraction.js, src/reviewRenderer/tpl/interactions/extendedTextInteraction.tpl, test/reviewRenderer/interactions/extendedText/test.js
=> Release 0.17.1

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/PortableCustomInteraction.js, src/qtiCommonRenderer/renderers/interactions/pci/common.js, src/qtiCommonRenderer/renderers/interactions/pci/ims.js, src/qtiCommonRenderer/renderers/interactions/pci/instanciator.js, test/qtiCommonRenderer/interactions/pci/common/qtiCustomInteractionContextMock.js, test/qtiCommonRenderer/interactions/pci/common/test.html, test/qtiCommonRenderer/interactions/pci/common/test.js, test/qtiCommonRenderer/interactions/pci/ims/test.html, test/qtiCommonRenderer/interactions/pci/ims/test.js, test/qtiCommonRenderer/interactions/pci/instanciator/test.html, test/qtiCommonRenderer/interactions/pci/instanciator/test.js
=> Release 0.18.0

package-lock.json, package.json, src/qtiCommonRenderer/helpers/data/mimeTypes.js, src/qtiCommonRenderer/helpers/uploadMime.js
=> Release 0.19.0

package-lock.json, package.json, src/qtiCommonRenderer/helpers/data/mimeTypes.js
**Relates to:** [AUT-15](https://oat-sa.atlassian.net/browse/AUT-15)
**Changes:**
* Some MIME-types were changed to the right values;
* Added missed equivalents for better filtering;
* Some names were changed to explain their content.
=> Fix/AUT-15/Fix MIME-type options

package-lock.json, package.json, src/qtiCommonRenderer/helpers/data/mimeTypes.js
=> Release 0.19.1

package-lock.json, package.json, src/qtiCommonRenderer/helpers/data/mimeTypes.js
**Relates to:** [AUT-15](https://oat-sa.atlassian.net/browse/AUT-15)
**Changes:** added equivalent for `.xps` extension (for better filtering).
=> Fix/AUT-15/Add XPS equivalent

package-lock.json, package.json, src/qtiCommonRenderer/helpers/data/mimeTypes.js
=> Release 0.19.2

package-lock.json, package.json, src/reviewRenderer/helpers/pci.js
=> Release 0.20.0

package-lock.json, package.json, src/reviewRenderer/renderers/interactions/PortableCustomInteraction.js
=> Release 0.21.0

src/qtiCommonRenderer/renderers/interactions/PortableCustomInteraction.js, src/qtiCommonRenderer/renderers/interactions/pci/common.js, src/qtiCommonRenderer/renderers/interactions/pci/ims.js, src/qtiCommonRenderer/renderers/interactions/pci/instanciator.js, src/qtiItem/core/interactions/CustomInteraction.js, test/qtiCommonRenderer/interactions/pci/common/qtiCustomInteractionContextMock.js, test/qtiCommonRenderer/interactions/pci/common/test.html, test/qtiCommonRenderer/interactions/pci/common/test.js, test/qtiCommonRenderer/interactions/pci/ims/test.html, test/qtiCommonRenderer/interactions/pci/ims/test.js, test/qtiCommonRenderer/interactions/pci/instanciator/test.html, test/qtiCommonRenderer/interactions/pci/instanciator/test.js
Related to: https://oat-sa.atlassian.net/browse/TR-907
Backport of #146
=> Hotfix/TR-508/Implement IMS PCI onready

src/qtiCommonRenderer/renderers/interactions/pci/ims.js, src/reviewRenderer/renderers/interactions/PortableCustomInteraction.js, test/qtiCommonRenderer/interactions/pci/ims/test.js
Related to: https://oat-sa.atlassian.net/browse/TR-907
Backport of #157
=> Hotfix/TR-663/restore IMS PCI state in review mode

src/reviewRenderer/helpers/pci.js
Related to: https://oat-sa.atlassian.net/browse/TR-907
Backport of #159
=> Hotfix/TR-765/Load test taker response in audio PCI

src/reviewRenderer/renderers/interactions/PortableCustomInteraction.js
Related to: https://oat-sa.atlassian.net/browse/TR-907
Backport of #161
=> Hotfix/MS-988/Audio PCI

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/AssociateInteraction.js, src/qtiCommonRenderer/tpl/interactions/associateInteraction.pair.tpl
Related to: https://oat-sa.atlassian.net/browse/TR-988
- backport of https://oat-sa.atlassian.net/browse/TR-830
Requires:
=> Chore/tr 988/backport tr 830

package-lock.json, package.json, src/qtiCommonRenderer/helpers/sizeAdapter.js
=> Release 0.21.4

package-lock.json, package.json, src/reviewRenderer/renderers/interactions/ExtendedTextInteraction.js
=> Release 0.21.5

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/UploadInteraction.js, src/qtiCommonRenderer/tpl/interactions/uploadInteraction.tpl, src/reviewRenderer/renderers/interactions/UploadInteraction.js, src/reviewRenderer/tpl/interactions/uploadInteraction.tpl
=> Release 0.21.6

package-lock.json, package.json, src/qtiCommonRenderer/helpers/sizeAdapter.js, src/qtiCommonRenderer/renderers/interactions/ChoiceInteraction.js
=> Release 0.21.7

package-lock.json, package.json, src/qtiCommonRenderer/renderers/Math.js
=> Release 0.21.8

src/qtiItem/helper/simpleParser.js, test/qtiItem/helper/simpleParser/test.js
**Related Issue :** https://oat-sa.atlassian.net/browse/AUT-560 
If user added the Table via CK Editor to the Passage during it's authoring, this Table will not display if the passage containing it will be added to the item during Item Authoring.
**Preconditions**: Passage containing table is created.
- Go to Items tab.
- 
- Create a new item and go to it's authoring.
- 
- Add any interaction to the canvas.
- 
- Add a Passage containing Table to this interaction.
**Actual result:** The Passage is added, the Table is not displayed in Item Authoring page.
**Expected result:** The Passage is added, all of it's contend is displayed including Table.
Env : http://tao-test-alshoja.playground.kitchen.it.taocloud.org:46031/
=> fix : simple parser upgraded for table rendering

package-lock.json, package.json, src/qtiItem/helper/simpleParser.js, test/qtiItem/helper/simpleParser/test.js
=> Release 0.21.9

package-lock.json, src/qtiCommonRenderer/renderers/interactions/OrderInteraction.js
**Related to:** https://oat-sa.atlassian.net/browse/AUT-192
**How to test**
1. Log in as Admin in Chrome or Internet Explorer
2. Choose 'Items' tab
3. Choose item and click 'Authoring' button
4. Choose 'Response' tab of interaction and set choice sequence that is different from order in which choices are listed in 'Question' tab
5. Choose 'Question' tab and observe choice sequence
6. Choice options should preserve initial order in which they are created upon adding Order Interaction onto canvas
Env: http://test-anastasia-2.playground.kitchen.it.taocloud.org:45401/
=> Fix/aut 192/wrong choices order

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/OrderInteraction.js
=> Release 0.21.11

package-lock.json, package.json, src/runner/provider/qti.js
=> Release 0.23.0

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/GraphicAssociateInteraction.js
=> Release 0.23.1

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js, test/qtiCommonRenderer/interactions/extendedText/test.html, test/qtiCommonRenderer/interactions/extendedText/test.js
=> Release 0.24.0

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/SliderInteraction.js
=> Release 0.26.0

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/InlineChoiceInteraction.js, test/qtiCommonRenderer/interactions/inlineChoice/test.js
=> Release 0.27.0

package-lock.json, package.json
Related to https://oat-sa.atlassian.net/browse/TR-2827
TODO: 
This doesn't include any actual change, but since we made changes in `tao-core-ui-fe` for the sake of MediaInteraction, I suppose we must update version here too and run tests.
=> Fix/tr 2827/mediaplayer maxplays show controls

package-lock.json, package.json
=> Release 0.27.1

package-lock.json, package.json
=> Release 0.27.2

package-lock.json, package.json
=> Release 0.27.3

package-lock.json, package.json, src/qtiItem/core/Loader.js
=> Release 0.28.0

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/pci/ims.js, test/qtiCommonRenderer/interactions/pci/ims/test.js
=> Release 0.29.0

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
=> Release 0.29.2

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ChoiceInteraction.js, test/qtiCommonRenderer/interactions/choice/test.js
=> Release 0.30.0

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js, src/qtiCommonRenderer/tpl/interactions/constraints/count.tpl, src/qtiCommonRenderer/tpl/interactions/extendedTextInteraction.tpl
=> Release 1.0.0

package-lock.json, package.json, src/qtiItem/core/interactions/CustomInteraction.js, src/qtiItem/helper/maxScore.js, test/qtiItem/maxScore/test.js
=> Release 1.1.0

package-lock.json, package.json, src/reviewRenderer/renderers/interactions/PortableCustomInteraction.js
Backport of https://github.com/oat-sa/tao-item-runner-qti-fe/pull/270
Also fix of eve.git issue
=> Hotfix/aut 2151/PCI renderer

package-lock.json, package.json, src/reviewRenderer/renderers/interactions/PortableCustomInteraction.js
=> Release 1.1.3

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/MediaInteraction.js
=> Release 1.1.4

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/MediaInteraction.js, test/qtiCommonRenderer/interactions/media/test.js
=> Release 1.1.5

package-lock.json, package.json, src/qtiCommonRenderer/helpers/sizeAdapter.js
2/2
Releated to [AUT-2088](https://oat-sa.atlassian.net/browse/AUT-2088)
**Requires:**
* Needed by [tao-qti-item](https://github.com/oat-sa/extension-tao-itemqti/pull/2121)
=> FIX/AUT-2088 Fix horizontal size choices

package-lock.json, package.json, src/qtiCommonRenderer/helpers/sizeAdapter.js
=> Release 1.1.7

package-lock.json, package.json
related to [AUT-2088](https://oat-sa.atlassian.net/browse/AUT-2088)
Fixed wrong dependency from branch to release
=> fix/AUT-2088 fix: update dependency

package-lock.json, package.json
=> Release 1.1.8

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js, test/qtiCommonRenderer/interactions/extendedText/test.html, test/reviewRenderer/interactions/extendedText/test.html
=> Release 1.1.9

package-lock.json, package.json, src/reviewRenderer/renderers/interactions/ExtendedTextInteraction.js
=> Release 1.1.10

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ChoiceInteraction.js, src/qtiCommonRenderer/renderers/interactions/OrderInteraction.js
=> Release 1.3.1

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js, src/reviewRenderer/renderers/interactions/ExtendedTextInteraction.js
=> Release 1.3.3

package-lock.json, package.json, src/qtiCommonRenderer/helpers/PortableElement.js, src/qtiCommonRenderer/renderers/interactions/InlineChoiceInteraction.js
=> Release 1.4.0

src/qtiCommonRenderer/renderers/interactions/InlineChoiceInteraction.js
Related to https://oat-sa.atlassian.net/browse/TR-4451
=> Hotfix/tr 4452/inline choice empty label text

package-lock.json, package.json, src/qtiItem/helper/maxScore.js
=> Release 1.4.1

package-lock.json, package.json, src/qtiCommonRenderer/helpers/itemStylesheetHandler.js
=> Release 1.5.0

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/InlineChoiceInteraction.js
=> Release 1.5.1

package-lock.json, package.json, src/qtiItem/helper/maxScore.js
=> Release 1.6.0

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ChoiceInteraction.js
=> Release 1.6.1

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ChoiceInteraction.js
Backport of https://github.com/oat-sa/tao-item-runner-qti-fe/pull/319 to [September Release](https://github.com/oat-sa/tao-community/blob/2022.09.3/composer.json#L39) to [taoQtiItem v29.11.3](https://github.com/oat-sa/extension-tao-itemqti/blob/v29.11.3/views/package.json#L12)
=> hotfix/AUT-2713 Choice interaction - Incorrect amount of choices are allowed to be selected if maxChoices = minChoices

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ChoiceInteraction.js
Related to: https://oat-sa.atlassian.net/browse/AUT-2713
Backport of https://github.com/oat-sa/tao-item-runner-qti-fe/pull/319 to [October Release](https://github.com/oat-sa/tao-community/blob/2022.10.2/composer.json#L39) in [taoQtiItem v29.12.4.1](https://github.com/oat-sa/extension-tao-itemqti/blob/v29.12.4.1/views/package.json#L12)
=> Hotfix: Choice interaction - Incorrect amount of choices are allowed to be selected if maxChoices = minChoices

package-lock.json, package.json, src/qtiCommonRenderer/helpers/Graphic.js
=> Release 1.6.2

package-lock.json, package.json, src/qtiItem/helper/xmlNsHandler.js
=> Release 1.6.3

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/AssociateInteraction.js
=> Release 1.6.4

package-lock.json, package.json, src/qtiCommonRenderer/renderers/Figure.js, src/qtiCommonRenderer/tpl/figure.tpl
=> Release 1.6.5

package-lock.json, package.json, src/qtiCommonRenderer/renderers/Figure.js, src/qtiCommonRenderer/tpl/figure.tpl
=> Release 1.7.1

package-lock.json, package.json, src/qtiCommonRenderer/renderers/choices/InlineChoice.js, src/qtiCommonRenderer/renderers/interactions/InlineChoiceInteraction.js, src/qtiCommonRenderer/tpl/choices/inlineChoice.tpl, src/qtiCommonRenderer/tpl/interactions/inlineChoiceInteraction.tpl, src/qtiItem/core/choices/ContainerInlineChoice.js, src/qtiItem/core/choices/InlineChoice.js, src/reviewRenderer/renderers/interactions/InlineChoiceInteraction.js, src/reviewRenderer/tpl/interactions/inlineChoiceInteraction.tpl, test/qtiCommonRenderer/interactions/inlineChoice/test.js, test/samples/json/richardIII-1.json
=> Release 1.8.0

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js, src/qtiCommonRenderer/renderers/interactions/TextEntryInteraction.js, test/qtiCommonRenderer/interactions/extendedText/test.html, test/qtiCommonRenderer/interactions/extendedText/test.js, test/qtiCommonRenderer/interactions/textEntry/test.js
=> Release 1.9.0

package-lock.json, package.json, src/qtiCommonRenderer/helpers/Graphic.js, src/qtiCommonRenderer/renderers/interactions/GraphicAssociateInteraction.js, src/qtiCommonRenderer/renderers/interactions/GraphicGapMatchInteraction.js, src/qtiCommonRenderer/renderers/interactions/GraphicOrderInteraction.js, src/qtiCommonRenderer/renderers/interactions/HotspotInteraction.js, src/qtiCommonRenderer/renderers/interactions/SelectPointInteraction.js
Related to: https://oat-sa.atlassian.net/browse/AUT-2869
https://oat-sa.atlassian.net/browse/INV-624
Backport of https://github.com/oat-sa/tao-item-runner-qti-fe/pull/351 to November Release [taoQtiItem 29.14.4.6](https://github.com/oat-sa/tao-community/blob/2022.11.11/composer.json#L39)  to ["@oat-sa/tao-item-runner-qti": "1.6.6"](https://github.com/oat-sa/extension-tao-itemqti/blob/v29.14.4.6/views/package.json#L12)
=> Hotfix/aut 2869/responsive background graphic interactions

package-lock.json, package.json, src/qtiItem/core/Loader.js
=> Release 1.9.2

package-lock.json, package.json
=> Release 1.9.4

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ChoiceInteraction.js
=> Release 1.10.1

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ChoiceInteraction.js
This backports #363 in order to add it on top of https://github.com/oat-sa/extension-tao-itemqti/blob/29.6.12/views/package.json
=> Fix TR-5398 backport unwanted style removal on choice interaction validation

package-lock.json, package.json, src/qtiCommonRenderer/renderers/Math.js, src/qtiCommonRenderer/renderers/interactions/AssociateInteraction.js
=> Release 1.11.0

package-lock.json, package.json, src/qtiCommonRenderer/renderers/Math.js, src/qtiCommonRenderer/renderers/interactions/AssociateInteraction.js
coming from [https://oat-sa.atlassian.net/browse/AUT-3093](https://oat-sa.atlassian.net/browse/AUT-3093)
changelog: adds math behavior to expressions on associate interaction
=> Backport/aut 3093/math expression fix

package-lock.json, package.json, src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
=> Release 1.11.2

package-lock.json, test/qtiCommonRenderer/interactions/graphicOrder/test.js
+ BEFORE :: 8 vulnerabilities (4 moderate, 1 high, 3 critical)
+ AFTER :: 6 vulnerabilities (2 moderate, 1 high, 3 critical)
Issue libs left: lodash, select2, uglify
dev tests had the following issue:
```
Timeout : test/qtiCommonRenderer/interactions/graphicOrder/test.html #
Test run could not finish in 30000ms
```
it was caused by uppercase letter in a path. Fixd
=> Chore: TR-3008 update 3rd party dependencies

.github/workflows/release-package.yml
Adds autorelease workflow file
=> chore: add autorelease workflow file

.github/workflows/continuous-integration.yml, package-lock.json, package.json
Update version of slavcodev/coverage-monitor-action@v1
=> chore: update coverage-monitor-action to v1

src/qtiItem/helper/maxScore.js
Ticket: https://oat-sa.atlassian.net/browse/AUT-3585
- Fixed MAXSCORE increasing
- Create an item with two or more interactions.
- Save the item few times.
- Check the MAXSCORE is not increasing every time.
=> fix: MAXSCORE increasing

package-lock.json, package.json, src/qtiCommonRenderer/renderers/Figure.js
This allows to center an image via QTI Item Creator
[AUT-3769]: https://oat-sa.atlassian.net/browse/AUT-3769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature AUT-3769 Support centering image

package-lock.json, package.json
=> Release 2.6.5

src/qtiCommonRenderer/renderers/Object.js, src/qtiCommonRenderer/renderers/interactions/MediaInteraction.js, src/qtiItem/core/interactions/BlockInteraction.js, src/qtiItem/core/interactions/Interaction.js, src/qtiItem/core/interactions/MatchInteraction.js, src/qtiRunner/core/Renderer.js, src/qtiRunner/modalFeedback/inlineRenderer.js
Include resource metadata url with transcription metadata in preview options;
=> Feat/aut 4110/transcription in media player

src/qtiItem/core/response/SimpleFeedbackRule.js
https://oat-sa.atlassian.net/browse/AUT-4259
- Add score based options to Modal Feedbacks
=> fix: add score based conditions
