- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
There was a small JS change in the repo we are about to migrate all the JS out of: https://github.com/oat-sa/extension-tao-itemqti/pull/1303/files
I have to import the small change into the npm package and re-release it, so that everything is preserved when we delete all the old JS sources (https://github.com/oat-sa/extension-tao-itemqti/pull/1299) and install the package.
`npm i && npm run test` to check it works.
> Fix/nex 91/import js changes before merge

- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/interactions/AssociateInteraction.js
**task:** https://oat-sa.atlassian.net/browse/TAO-8725
**description:** 
on hybrid laptops ( both with keyboard and touchscreen) all plugins (widgets) of test runner were unable to move through the touchscreen instead of mouse or touchpad. 
At this particular package there was a problem with fired events order for dragged and dropable components.
**solution**
Was decided to postpone draggable element *drag end* and fire it after dropable element.
**related PR**
https://github.com/oat-sa/tao-core/pull/2251
> TAO-8725 draggable event executed before dropzone

- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/interactions/GraphicOrderInteraction.js
Related to: https://oat-sa.atlassian.net/browse/TAO-9085
Related PR: https://github.com/oat-sa/extension-tao-itemqti/pull/1336
The issue:  if `maxChoices = size of choices` then condition `if (max > 0 && max < size) {` didn't match and  `} else if (min > 0 && min < size) {
size = min;
}` So the size set in minChoices
https://github.com/oat-sa/tao-item-runner-qti-fe/blob/f7d7bb46f3d9e579dd8011215a942454709d07a7/src/qtiCommonRenderer/renderers/interactions/GraphicOrderInteraction.js#L115-L126
https://github.com/oat-sa/extension-tao-itemqti/blob/02b6cd67f00ffe5e2ca9d1ee2403a2e351e94023/views/js/qtiCreator/widgets/interactions/graphicOrderInteraction/Widget.js#L78-L90
Fix:
In calculation, minChoices and maxChoices can be equal to the size of choices.
**Changes in 2 files in …
> fix/TAO-9085/minChoices and maxChoices can be equal to the size of choices

- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/interactions/ChoiceInteraction.js
- src/qtiCommonRenderer/renderers/interactions/GapMatchInteraction.js
- src/qtiCommonRenderer/renderers/interactions/GraphicGapMatchInteraction.js
- src/qtiCommonRenderer/renderers/interactions/MatchInteraction.js
- src/qtiCommonRenderer/renderers/interactions/OrderInteraction.js
**Related to task:** 
https://oat-sa.atlassian.net/browse/NEC-31
When test-taker returns to an item with Gap Match interaction (from graphic interactions) which has a choice identifier that includes full stop "." (e.g. "LT_2019_6kl_6.3_b") system throws error: 
Error: Syntax error, unrecognized expression: [data-identifier=LT_2019_6kl_6.3_b] 
**How to test:**
Import test from the ticket and test with: 
- choice interaction;
- gap match interaction;
- graphic gap match interaction
- match interaction
- order interaction
> Fix/nec 31/escape attrib equals selector=

- package.json
- src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
https://oat-sa.atlassian.net/browse/TAO-9922 WTP-1493
[ACT] - On writing item, text is always pasted to the end.
prepare TAO instance, go to taoQtiItem/views/package.json and replace current depencies
`  "dependencies": {
...
"@oat-sa/tao-item-runner-qti": "0.4.9"
}`
with this branch:
`  "dependencies": {
...
"@oat-sa/tao-item-runner-qti": "github:oat-sa/tao-item-runner-qti-fe#fix/TAO-9922/fix-paste-clipboard-to-textarea"
}`
then run `npm install` in directory `YOUR_PROJECT_ROOT/taoQtiItem/views/`
Login to prepared delivery and run the test with an any text area in the test item. Set focus on the textarea and type the words "one two three", then cut last word to the clipboard. Now set the text cursor between "one" and "two" and press keyboard shortcut to insert word "three". Result must …
> fixed new string value on clipboard paste

- package-lock.json
- package.json
- src/qtiCommonRenderer/helpers/itemStylesheetHandler.js
Error with the event 'customcssloaded.styleeditor'
After Preview was moved from iframe to document https://oat-sa.atlassian.net/browse/TAO-8134
event from iframe now in the same document as editor.
How to test:
1. go to the Items page
2. go to Authoring
3. go to Preview
> fix error with event customcssloaded.styleeditor

- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/interactions/SliderInteraction.js
**Related to: https://oat-sa.atlassian.net/browse/UDI-31**
SliderInteraction has HTML tags in markup that depends on `attribute.responseIdentifier`. 
`attribute.responseIdentifier` used as part of id
But we have the case when there is only one interaction remaining, its `reponseIdentifier` must be `RESPONSE`
see https://github.com/oat-sa/extension-tao-itemqti/blob/16433c115d28530a40b8278da6c3f2afac5eece7/views/js/qtiCreator/model/mixin/editableInteraction.js#L125-L138
so we need to handle this and change id of related tags
**Related to:** 
**How to test:**
Adding a slider interaction
Defining response
Save and preview
--> everything OK
Adding a new slider
Deleting the first one
Defining response for the new one
Saving and preview
--> I'm getting correct score before answering
--> The …
> fix/UDI-31/handle change of attribute responseIdentifier

- package-lock.json
- package.json
- src/qtiCommonRenderer/tpl/choices/simpleChoice.choiceInteraction.tpl
- src/qtiCommonRenderer/tpl/interactions/choiceInteraction.tpl
- src/qtiCommonRenderer/tpl/interactions/extendedTextInteraction.tpl
- src/qtiCommonRenderer/tpl/interactions/prompt.tpl
- src/qtiItem/core/interactions/BlockInteraction.js
**Jira ticket:**
https://oat-sa.atlassian.net/browse/ACTP-315
Added reading text question to extended text and simple choice interactions response and added reading choices to the simple choice interaction
**How to test:**
1. Change locally `package.json` file in `tao-qti-item/views`, `@oat-sa/tao-item-runner-qti` dependency version should be: `git@github.com:oat-sa/tao-item-runner-qti-fe.git#feature/ACTP-315/a11y-Choice-Interaction-and-Text-Entry-reponse-item`
2. Run `npm i`
3. Create test with simple choice items and extended text
4. Enable screen reader
5. Run the test as test taker. Question and choices should be readable, when the response item receives the focus
> Feature/actp 315/a11y choice interaction and text entry reponse item

- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/interactions/TextEntryInteraction.js
**Related to**
https://oat-sa.atlassian.net/browse/BOSA-36
Inline text entry, when you click on the hole in the text, it appears directly "This is not a valid answer": even though you haven't written anything yet. This appears when you select a pattern mask that matches 0 value.
> BOSA 36 - Hidden tooltip when pattern mask matches with 0 value

- .gitignore
- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/interactions/TextEntryInteraction.js
- test/qtiCommonRenderer/interactions/textEntry/test.js
**Related to**
https://oat-sa.atlassian.net/browse/BSA-36
**Fix other cases not covered by**
https://github.com/oat-sa/extension-tao-itemqti/pull/1426
**Other necessary PR to be merged for seeing complete feature working**
https://github.com/oat-sa/extension-tao-itemqti/pull/1436
Avoid error message appears in any case before the user write something
**AC**
> BSA 36 - Avoid error message appears in any case before user write something

- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
Related to: https://oat-sa.atlassian.net/browse/TAO-10178
Added checking pattern for XHTML format in Extended text Interaction.
How to test:
1. Create an item with Extended text Interaction.
2. In Interaction properties select Pattern constraint and set pattern ^[A-z]{2,}$.
3. Choose Format XHTML.
4. Save and Preview.
5. In Preview type some digits in response section (f.e. 123).
6. Expected result: 'This is not a valid answer' message should appear when typed text is violating Pattern constraint
> Fix/tao 10178/extended text interaction xhtml check patter

- package-lock.json
- package.json
- src/qtiCommonRenderer/tpl/img.tpl
Related to: https://oat-sa.atlassian.net/browse/TBD-22
QTI runner renders a responsive image with a redundant style: width=<n>, that should be removed, as the image's width is being controlled by a width attribute.
Before fix
After fix
How to test:
1. create an item with an image
2. set a responsive mode for image
3. preview image and check tag style
> Fix/tbd 22/clean up responsive image style

- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
Related to : https://oat-sa.atlassian.net/browse/TCA-519
Update extended text interaction to take content from data-clipboard if it available when handling copy event
- prepare an instance of TAO with taoAct extension
- prepare a delivery which includes extended text interaction with some constraints
- enable security mode for the delivery
- execute the delivery as a test taker and try to copy/paste to the text interaction
Companion PR :
> Release 0.6.2

- package-lock.json
- package.json
- src/reviewRenderer/renderers/config.js
- src/reviewRenderer/renderers/interactions/MediaInteraction.js
Ticket: https://oat-sa.atlassian.net/browse/MS-137
* Media interaction in review Renderer now has different settings to make the user experience of scorer better. Every media interaction will have the following settings regardless of what is set in authoring for test-taker:
- Can be player infinite times
- Can pause
- Can seek
- autoplay: false
- volume: 80 (Max is 100)
- loop: false
- https://github.com/oat-sa/extension-tao-itemqti/pull/1451
- Checkout this branch in tao-item-qti: `feature/MS-147/enhanced-readonly-mode`
- Install node modules in tao-item-qti
- Create an item with media interactions and add some restrictions (can be played only once, cant pause, etc)
- Preview the item, you should see it as expected and restrictions should be respected
- Take the test, you should again …
> media interaction for review mode

- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
Backport https://github.com/oat-sa/tao-item-runner-qti-fe/pull/67
Related to: https://oat-sa.atlassian.net/browse/TAO-10178
Added checking pattern for XHTML format in Extended text Interaction.
How to test:
1. Create an item with Extended text Interaction.
2. In Interaction properties select Pattern constraint and set pattern ^[A-z]{2,}$.
3. Choose Format XHTML.
4. Save and Preview.
5. In Preview type some digits in response section (f.e. 123).
6. Expected result: 'This is not a valid answer' message should appear when typed text is violating Pattern constraint
> Hotfix/tao 10178/extended text interaction xhtml check patter

- package-lock.json
- package.json
- src/qtiCommonRenderer/tpl/img.tpl
Related to : https://oat-sa.atlassian.net/browse/TCA-638
Apply aria attributes to images
- prepare an instance of TAO
- import test assigned to https://oat-sa.atlassian.net/browse/TCA-604
- executed delivery created from test as a test taker
- make sure that aria attributes are in place
Companion PR :
> [TCA-638] Adjusting template to include ARIA attributes

- package-lock.json
- package.json
- src/qtiCommonRenderer/tpl/choices/simpleChoice.choiceInteraction.tpl
Related to : https://oat-sa.atlassian.net/browse/TCA-737
remove `aria-labelledby` attribute from simple choice interaction
- prepare an instance of TAO with taoAct extension
- prepare a delivery with choice interaction and accessibility mode enabled
- execute delivery as a test taker
- make sure that choice items do not have `aria-labelledby` attribute
Companion PR :
> [TCA-737] Screen Reader : Answer options announced multiple times

- package-lock.json
- package.json
- src/qtiCommonRenderer/tpl/choices/simpleChoice.choiceInteraction.tpl
Related to : https://oat-sa.atlassian.net/browse/TCA-737
remove `aria-labelledby` attribute from simple choice interaction
- prepare an instance of TAO with taoAct extension
- prepare a delivery with choice interaction and accessibility mode enabled
- execute delivery as a test taker
- make sure that choice items do not have `aria-labelledby` attribute
Companion PR :
> Release 0.10.2

- package-lock.json
- package.json
- src/qtiCommonRenderer/tpl/interactions/extendedTextInteraction.tpl
Related to : https://oat-sa.atlassian.net/browse/CTCA-154
Change label chars to characters in text interactions constraints label
- prepare an instance of TAO
- prepare a delivery with text interactions which contains some constraints
- execute delivery as a test taker
- check that constraints label contains `characters` instead of `chars`
Requires :
> [CTCA-154] Screen Reader : Character count has an unusual abbreviation.

- package-lock.json
- package.json
- src/qtiCommonRenderer/tpl/interactions/extendedTextInteraction.tpl
Related to : https://oat-sa.atlassian.net/browse/CTCA-154
Change label chars to characters in text interactions constraints label
- prepare an instance of TAO
- prepare a delivery with text interactions which contains some constraints
- execute delivery as a test taker
- check that constraints label contains `characters` instead of `chars`
Requires :
> Release 0.10.3

- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/interactions/TextEntryInteraction.js
- src/qtiCommonRenderer/tpl/interactions/textEntryInteraction.tpl
**Related to**
https://oat-sa.atlassian.net/browse/UNO-467
**As** content creator
**I would** like during the assessment on textEntry interaction and in case of touch-based devices, to open the numeric keyboard for input
**so that**  we increase user experience and eliminate possibilities for wrong input
**Acceptance Criteria**
**AC1**
**GIVEN** an inline `textEntry` interaction flagged as expecting a numeric input
**WHEN** the test taker tap on the input field with a touch-based device like a tablet
**THEN** the device opens the numeric keyboard instead of the alphanumeric keyboard
**Considerations**
The main goal is to implement this story on the NextGen test runner.
- NextGen test runner
Implementation of NextGen test runner already support such behavior.  We have to …
> Feature UNO 467 - Extend Response Properties on text Entry interaction with possibility to set baseType property

- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/interactions/TextEntryInteraction.js
- test/qtiCommonRenderer/interactions/textEntry/test.html
- test/qtiCommonRenderer/interactions/textEntry/test.js
- test/samples/json/text-entry-inputmode-float.json
- test/samples/json/text-entry-inputmode-integer.json
- test/samples/json/text-entry-inputmode-text.json
**Related to**
https://oat-sa.atlassian.net/browse/UNO-467
Based on https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode change `inputmode` to support default `text` attribute
> [Fix] UNO 467 - Support correct version for default on render numerical input

- package-lock.json
- package.json
- src/qtiItem/core/Loader.js
- src/qtiItem/helper/response.js
- src/qtiItem/helper/responseRules.js
- test/qtiItem/core/loader/test.html
- test/qtiItem/core/loader/test.js
- test/qtiItem/core/loader/testQtiClass.js
- test/qtiItem/helper/response/test.html
- test/qtiItem/helper/response/test.js
- test/qtiItem/helper/responseRules/test.html
- test/qtiItem/helper/responseRules/test.js
Related to : https://oat-sa.atlassian.net/browse/TAO-10497
Refactor QTI item loader to recognize response processing type by response rules
**NOTE**:
QTI item loader was refactored to ES6 syntax this changes done in [separated commit](https://github.com/oat-sa/tao-item-runner-qti-fe/pull/104/commits/d64bb90b657b5f811452fedea7dd023aea6e151f) . Actual changes made in this [commit](https://github.com/oat-sa/tao-item-runner-qti-fe/pull/104/commits/48bd449d5d936e993aedfe98749e85785f0369b9)
- prepare an instance of TAO with `xmlEdit` and `xmlEditRp ` installed
- prepare an item with interactions with different response processing templates
- try to open item for authoring. make sure that response processing templates properly recognized
- prepare an item with custom response processing
- try to …
> [TAO-10497] R&O Processing - Refactor qti item loader

- package-lock.json
- package.json
- src/qtiItem/core/Loader.js
- src/qtiItem/helper/response.js
- src/qtiItem/helper/responseRules.js
- test/qtiItem/core/loader/test.html
- test/qtiItem/core/loader/test.js
- test/qtiItem/core/loader/testQtiClass.js
- test/qtiItem/helper/response/test.html
- test/qtiItem/helper/response/test.js
- test/qtiItem/helper/responseRules/test.html
- test/qtiItem/helper/responseRules/test.js
Related to : https://oat-sa.atlassian.net/browse/TAO-10497
Refactor QTI item loader to recognize response processing type by response rules
**NOTE**:
QTI item loader was refactored to ES6 syntax this changes done in [separated commit](https://github.com/oat-sa/tao-item-runner-qti-fe/pull/104/commits/d64bb90b657b5f811452fedea7dd023aea6e151f) . Actual changes made in this [commit](https://github.com/oat-sa/tao-item-runner-qti-fe/pull/104/commits/48bd449d5d936e993aedfe98749e85785f0369b9)
- prepare an instance of TAO with `xmlEdit` and `xmlEditRp ` installed
- prepare an item with interactions with different response processing templates
- try to open item for authoring. make sure that response processing templates properly recognized
- prepare an item with custom response processing
- try to …
> Release 0.12.0

- package-lock.json
- package.json
- src/qtiItem/core/Loader.js
- src/qtiItem/helper/itemScore.js
- src/qtiItem/helper/response.js
- src/qtiItem/helper/responseRules.js
- test/qtiItem/core/loader/test.js
- test/qtiItem/helper/responseRules/test.html
- test/qtiItem/helper/responseRules/test.js
Related to : https://oat-sa.atlassian.net/browse/TAO-10497
Add support of per interaction response processing to qti item loader
NOTE:
Functionality available only thought additional param of qti item loader. can be tested on playground env provided in the comment for ticket 
- prepare an instance of TAO with `xmlEdit` and `xmlEditRp ` installed
- prepare an item with interactions with different response processing templates
- try to open item for authoring. make sure that response processing templates properly recognized and missing outcome declaration created
- change item response processing to custom and use per interaction response template form confluence document https://oat-sa.atlassian.net/wiki/spaces/NEX/pages/483557803/Authoring+interaction+level+item+scores
- try to open item …
> [TAO-10499] R&O Processing - Add support of per interaction response processing to item loader

- package-lock.json
- package.json
- src/qtiItem/core/Loader.js
- src/qtiItem/helper/itemScore.js
- src/qtiItem/helper/response.js
- src/qtiItem/helper/responseRules.js
- test/qtiItem/core/loader/test.js
- test/qtiItem/helper/responseRules/test.html
- test/qtiItem/helper/responseRules/test.js
Related to : https://oat-sa.atlassian.net/browse/TAO-10497
Add support of per interaction response processing to qti item loader
NOTE:
Functionality available only thought additional param of qti item loader. can be tested on playground env provided in the comment for ticket 
- prepare an instance of TAO with `xmlEdit` and `xmlEditRp ` installed
- prepare an item with interactions with different response processing templates
- try to open item for authoring. make sure that response processing templates properly recognized and missing outcome declaration created
- change item response processing to custom and use per interaction response template form confluence document https://oat-sa.atlassian.net/wiki/spaces/NEX/pages/483557803/Authoring+interaction+level+item+scores
- try to open item …
> Release 0.13.0

- package-lock.json
- package.json
- src/qtiCommonRenderer/helpers/uploadMime.js
Related to : https://oat-sa.atlassian.net/browse/TAO-10387
added file types for some mime types
- aopen any test item for authoring
- add file upload interaction to item
- save item and open item preview
- ensure selected Pascal, C, CSV, FLS, etc mime types correctly used as file type filter
Requires :
> fix mime type file extension for upload file interaction

- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
- src/reviewRenderer/renderers/interactions/ExtendedTextInteraction.js
- src/reviewRenderer/tpl/interactions/extendedTextInteraction.tpl
- src/runner/provider/qti.js
- test/reviewRenderer/interactions/extendedText/test.html
- test/reviewRenderer/interactions/extendedText/test.js
- test/runner/interactions/choice/test.js
- test/runner/provider/test.js
Ticket: https://oat-sa.atlassian.net/browse/MS-446
**What has changed?**
At the moment, the `reviewRenderer` is rendering the extended text interaction using a `textarea` and `ckEditor` plugin. This is not good when the scorer would like to highlight the response of a test taker (which is rendered inside the `textarea` component or an `iframe` component) because you can not get the `range` of the text which is not part of the dom. To achieve the highlight feature for scorers in the reviewRenderer I have changed the textarea and ckEditor iframe with a simple div and the response is injected in this div (plain text for simple extended interactions and rich html for xhtml extended text interaction)
**How to test?**
- Check out the branch
- install this version of node modules in taoQtiItems …
> change textarea and ckeditor to div

- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
- src/reviewRenderer/renderers/interactions/ExtendedTextInteraction.js
- test/qtiCommonRenderer/interactions/extendedText/test.js
- test/reviewRenderer/interactions/extendedText/test.js
Related to: https://oat-sa.atlassian.net/browse/TR-10
When an Extended Text interaction is set with a null response, it triggers an error. This is particularly annoying in the Test Reviewer, as empty responses are restored as null responses.
How to test:
- `npm run test`
Or see the companion PR.
> Fix/TR-10/Accept a null response in the Extended Text interaction

- .gitignore
- package-lock.json
- package.json
- src/reviewRenderer/helpers/pci.js
- src/reviewRenderer/renderers/interactions/PortableCustomInteraction.js
- test/reviewRenderer/helpers/pci/test.js
Ticket: https://oat-sa.atlassian.net/browse/MS-532
- Functionality to allow interaction in specific PCIs
- Create a test with text reader PCI and one more PCI (don't forget to add manual scoring flags)
- Publish the test and create a scoring project
- Give the test as a TT
- Login as a scorer on MS and try to interact with both the PCIs
- You should be able to interact with text reader but not wiht any other PCIs
https://github.com/oat-sa/extension-tao-itemqti/pull/1593
> Fix PCI in review renderer mode

- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
Related to: https://oat-sa.atlassian.net/browse/CON-173
Removed NO-BREAK SPACE in the end when new line added and all new line symbols from the count of characters - in commit https://github.com/oat-sa/tao-item-runner-qti-fe/pull/136/commits/87dc376de116d458b49bd1c0b12d5e4873c18d73
Fixed eslint errors and code style issues
How to test:
1. In 'Items' tab choose created item and click 'Authoring' button
2. Drag'n'drop Extended Text Interaction onto the canvas and choose 'XHTML' from drop-down menu of 'Format' field in Interaction Properties
3. Choose 'Max Length' from drop-down menu of 'Contraints' field and set 'Max length' value to positive integer
4. Enter text starting new paragraphs at new lines for several times using 'Enter' key and observe amount of used characters displayed in the …
> Fix/CON-173/Extended Text Interaction don't count new line as character

- src/scoring/processor/expressions/engine.js
- src/scoring/processor/expressions/expressions.js
Related to: https://oat-sa.atlassian.net/browse/AUT-2
There was a problem with the import of this module `src/scoring/processor/expressions/expressions`. After some dependencies update in #178 (judging from the package-lock of that PR it could be something in Babel), unit test now fails because the importing file loads the `'default'` property of the exported object, instead of the whole object.
```
export default { // <-- when trying to load this one,
'baseValue': baseValue,
'correct': correct,
'default': defaultt // <-- this one is loaded instead
}
```
**Fix:** add `'Processor'` suffix to the object keys and remove it at the other end. I've checked all `oat-sa` on Github and didn't find another import of the changed module. Even so, this could be released as a breaking change, to be …
> Fix unit test with default export problem

- environment/config.js
- package-lock.json
- package.json
- test/qtiCommonRenderer/interactions/graphicGapMatch/test.js
- test/qtiCommonRenderer/interactions/selectPoint/qti.json
Related to: https://oat-sa.atlassian.net/browse/CON-622
1. Updated "interactjs" to v1.3.4, because tao-core-ui uses "interactjs": "1.3.4"
https://github.com/oat-sa/tao-core-ui-fe/blob/6ff2aa4ac23dbc92abc59ac92bc63bfa5c9e0e4c/package.json#L62
2. Updated configs for select2
How to test:
- run `npm run test`
- all test should pass
> fix/CON-622/ Fix unit tests, update "interactjs" to v1.3.4

- src/qtiCommonRenderer/renderers/Math.js
In every interaction user is able to add Math Expression box and insert an equation in two modes: LaTeX and MathML. 
The issue is that in MathML mode after entering equation (using MathML code), clicking 'Done' or any free space and then typing some text after equation, it's structure becomes broken and remains in this state.
**Note**: Insert this MathML code into MathML text field:
`<mrow>
<mi>x</mi>
<mo>=</mo>
<mfrac>
<mrow>
<mrow>
<mo>-</mo>
<mi>b</mi>
</mrow>
<mo>&PlusMinus;</mo>
<msqrt>
<mrow>
<msup>
<mi>b</mi>
<mn>2</mn>
</msup>
<mo>-</mo>
<mrow>
<mn>4</mn>
<mo>&InvisibleTimes;</mo>
<mi>a</mi>
<mo>&InvisibleTimes;</mo>
<mi>c</mi>
</mrow>
</mrow>
</msqrt>
</mrow>
<mrow>
<mn>2</mn>
<mo>&InvisibleTimes;</mo>
<mi>a</mi>
</mrow>
</mfrac>
</mrow>
` …
> fix: MathMl render error

- src/qtiCommonRenderer/renderers/choices/InlineChoice.js
- src/qtiCommonRenderer/renderers/interactions/InlineChoiceInteraction.js
- src/qtiCommonRenderer/tpl/choices/inlineChoice.tpl
- src/qtiCommonRenderer/tpl/interactions/inlineChoiceInteraction.tpl
- src/qtiItem/core/choices/InlineChoice.js
- test/qtiCommonRenderer/interactions/inlineChoice/test.js
- test/samples/json/richardIII-1.json
**Related to:** https://oat-sa.atlassian.net/browse/AUT-22
**How to test**
- Create inline choice interaction
- Try to add different markup and math to the choices
- Add new / delete choices
- Save item
**Related PR:** https://github.com/oat-sa/extension-tao-itemqti/pull/1797
Env: http://test-anastasia.playground.kitchen.it.taocloud.org:44451/
> Feature/aut 22/add ckeditor to inline choice

- src/runner/provider/qti.js
It is part of work under [REL-470](https://oat-sa.atlassian.net/browse/REL-470)
The customer reported that some messages from this file showed but were not translated, my changes add the ability to translate such messages.
> Translate error messages because they are user-facing

- src/qtiCommonRenderer/renderers/interactions/pci/ims.js
- test/qtiCommonRenderer/interactions/pci/ims/test.js
related to https://oat-sa.atlassian.net/browse/TR-3246
PCI [configuration](https://www.imsglobal.org/spec/qti/v3p0/impl#h.1mc9puik2ft6) object is passed on pci instance creation. This PR brings population  of the config with language props.
Using DevTools check pciConstructor.getInstance is called with configured language in config object
> feat: retrieve languages from interaction definition and context

- src/qtiCommonRenderer/renderers/interactions/pci/ims.js
- test/qtiCommonRenderer/interactions/pci/ims/test.js
related to https://oat-sa.atlassian.net/browse/TR-3246
This fixes the misused context for userLanguage setup
Run unit tests:
`npm run test:keepAlive`
copy the link from console and add `/qtiCommonRenderer/interactions/pci/ims/test.html` to it
`http://127.0.0.1:<port>/test/qtiCommonRenderer/interactions/pci/ims/test.html`
> Fix/tr 3246/locale from shared context

- src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
**Related to:** [TR-3112](https://oat-sa.atlassian.net/browse/TR-3112)
IME characters are not being processed well with the pattern limit. I found a [CKEditor plugin](https://github.com/w8tcha/CKEditor-wordcount-Plugin) that supports it but we can't use it because we need to have separated the counter from the input. But it's handy to check how it manages IME characters. 
**Changes:**
- Add count bytes function to check the IME characters.
- Undo characters when they reach the limit. On CKEditor and on the textarea.
**How to check:**
- Install an IME tool on your OS, and enable the Japanese keyboard to write with it.
- Test on an ExtendedText interaction with length constrain pattern.
- Check if the limit works on English and on the IME language chosen.
> fix: limit IME chars on extendedText maxLength

- src/qtiItem/core/interactions/CustomInteraction.js
- src/qtiItem/helper/maxScore.js
- test/qtiItem/maxScore/test.js
**Related to:** [AUT-507](https://oat-sa.atlassian.net/browse/AUT-507)
on Match Correct response mode, we want to increment the MAXSCORE number with every interaction are added to the Item, even if it is a PCI.
**Changes:**
- Add a connection between CustomInteraction and the NomalMaximum param that MAXCORE depends on.
- Condition to be on Match Correct response mode and have a correct response declaration.
**How to check:**
- Add a PCI item with response mode, like Liquids. Set a correct response.
- Save it and check the XML on the `saveItem` action payload. Must have the param `normalMaximum` and the MAXSCORE outcome.
```
<outcomeDeclaration cardinality="single" baseType="float" identifier="SCORE" normalMaximum="1"/>
<outcomeDeclaration cardinality="single" …
```
> feat: add maxscore outcome to PCI on Match Correct Responses

- src/qtiCommonRenderer/renderers/interactions/InlineChoiceInteraction.js
Related to:
https://oat-sa.atlassian.net/browse/AUT-2123
https://github.com/oat-sa/extension-tao-itemqti/pull/2104
Fix inline interaction responses box not aligned correctly for RTL when first saved as LTR. 
Solution for **widget RESPONSE** side.
SETPS to test:
• Checkout to branch: fix/fix/AUT-2123/inlinechoice-interaction-responses-not-aligned-when-initially-saved-LTR
•Create an item
•Add a text block.
•Add an Inline Choice interaction.
•Click save with default language (LTR)
•Re-open and change language to RTL
**ACTUAL RESULT:**
the widget with the choices doesn't show the RTL alignment as the rest of the item.
**EXPECTED RESULT:**
When opening responses box alignment should be RTL  please make sure that you check in the RESPONSE" tickbox.
**CHANGES:**
`$ItemBody` wasn't getting the …
> fix: select2 dropdown RTL

- src/reviewRenderer/renderers/interactions/PortableCustomInteraction.js
Related to: https://oat-sa.atlassian.net/browse/AUT-2151
**On line 38 we need this === renderer** 
`markup = PortableElement.fixMarkupMediaSources(markup, this);`
**Preconditions:**
Item with Math entry PCI with the picture in prompt added to the test
Test passed by TT or guest
- Go to results tab and select the test
- Click “View“ 
- Click “Review“
**Actual result:** Math entry PCI interaction is not displayed in Test Review mode. error pops-up. Error in console
**Expected result:** Math entry PCI interaction is displayed in Test Review mode without any errors.
> fix: PortableCustomInteraction renderer need function to use this

- src/qtiCommonRenderer/renderers/interactions/MediaInteraction.js
Related to: https://oat-sa.atlassian.net/browse/AUT-2178
Regression after fix:
https://github.com/oat-sa/tao-item-runner-qti-fe/pull/262/files#diff-903b0c826874b1e9917b94ae77a002c935309dcab424c432a854d651e4ba339bR138-R140
**Solution:** move condition (if media interaction in old format == width in `px`, not in `%`) to `resize` function 
- Click the Items tab, create a new Item and click its "Authoring" button
- Drag and Drop a Media Interaction on the canvas
- Add the video file from Resource manager 
- Modify the Size value of Media Player and click outside the interaction area
- Observe the Media Interaction
**Actual result:** Media player adjusts to the size of Media Interaction container, video is displayed in the center on the black background
**Expected result:** Media Player can be …
> fix: resize Media interaction

- src/qtiCommonRenderer/renderers/interactions/MediaInteraction.js
- test/qtiCommonRenderer/interactions/media/test.js
PR template
Related to: [TR-4004](https://oat-sa.atlassian.net/browse/TR-4004)
Add null as the default(initial) value for media interaction to fix viewed and answered state
**Changes:**
*Changed `setResponse` and `getResponse` to fix the state for media interaction on runtime.
*Update Unit-test with removing play action, not necessary to the test case, and add a timeout to render to prevent triggering error after test execution
**How to check:**
* Create items with media interaction and choices interaction.
* Add multiple (3+) previously created items to the test 
* Start the test and play media once to set the item to answer state
* Move to the next one and do not interact click next
* Observe that one item has a circle icon(answered) another has an eye icon (viewed)
* …
> fix/TR-4004 Add default state null for media interaction

- src/qtiItem/helper/xincludeLoader.js
Related to: https://oat-sa.atlassian.net/browse/AUT-2028
**Problem:** XML is loaded only once for Items page
**Solution:** reset the previous definition of the XML, to receive updated passage
- Create a item with shared stimulus
- Open new tab with media, editing the shared stimuli, save
- Going back to the tab with item, closing the item by "mange items"
- Then clicking "authoring again"
**Actual:**  The shared stimuli change is not included
**Expected:** The item is updated with the new change in shared stimuli.
> fix: reset the previous definition of the XML, to receive updated passage

- src/qtiCommonRenderer/renderers/Math.js
Related to https://oat-sa.atlassian.net/browse/AUT-2270
Use with https://github.com/oat-sa/extension-tao-itemqti/pull/2171 
For each individual math element, MathJax  [Typeset](https://docs.mathjax.org/en/v2.0-latest/typeset.html#modifying-math-on-the-page) runs on all `.qti-item`, so if there are several elements, they are "typeset" several times. It's ok in delivery, but not in Authoring of `MathEntryInteraction` prompt (Probably html elements are cloned by Authoring, and [MathJax](https://github.com/mathjax/MathJax/blob/2.7.5/unpacked/MathJax.js#L2070) which seems to keep data about what was rendered in its objects doesn't recognize them as already processed)
**HISTORY:**
_(see ticket comments)_
1) First scope of "typeset" was `parent()` (_why parent, not self? for performance …
> Fix/aut 2270/mathentryinteraction math duplicated

- src/qtiCommonRenderer/renderers/interactions/InlineChoiceInteraction.js
Related to https://oat-sa.atlassian.net/browse/TR-4451
I need to override `--- leave empty ---` text for empty option from customer extension.
1) I think we can't simply remove old `__('leave empty')` key without possibly losing existing translations? Or is there a way to find all places where it's translated and change them?
2) Otherwise is there a way to pass a `emptyLabelText` option from customer extension to interaction? Like in Solar we use `propertyOverride` in `tenants.json`.
> Fix/tr 4451/inlinechoice empty label text

- src/qtiItem/helper/maxScore.js
related to https://oat-sa.atlassian.net/browse/AUT-1906
When response processing is turned off for interaction, SCORE and MAXSCORE outcome declarations are ignored and not saved into item xml, this PR allows them to be entered manually and saved
- run unit tests
- check with related PR (https://github.com/oat-sa/extension-tao-itemqti/pull/2191)
> fix: do not remove SCORE and MAXSCORE from outcomeDeclaration

- src/qtiCommonRenderer/renderers/interactions/InlineChoiceInteraction.js
Related to https://oat-sa.atlassian.net/browse/TR-4451
Use with https://github.com/oat-sa/extension-tao-itemqti/pull/2198
Follow-up to https://github.com/oat-sa/tao-item-runner-qti-fe/pull/305
InlineChoiceInteraction empty label text:
With that solution, existing translations would be lost, because even if language doesn't have `--- leave empty ---` defined, `__('--- leave empty ---')` will not return empty string, it will just return original text in english.
So just replace old  `'--- ' + __('leave empty') + ' ---'` with new `__('--- leave empty ---')` and update all existing translations.
> Fix/tr 4451/inlinechoice empty label lost translation

- src/qtiItem/helper/maxScore.js
Related to: https://oat-sa.atlassian.net/browse/TR-4504
**Calculate maximum for PCI with MAP_RESPONSE** 
Create item with Math PCI, save it - normalMaximum will be 0
Add answer, save it - normalMaximum will be 1
> feat: calculate normal maximum for PCI with MAP_RESPONSE

- src/qtiCommonRenderer/renderers/interactions/ChoiceInteraction.js
Related to: https://oat-sa.atlassian.net/browse/AUT-2713
- Create an Item and open it in Authoring
- D&D Choice Interaction to the canvas
- Select Multiple Choice and other Other constraints
- Set maxChoices = minChoices (e.g. 2) 
- Save and preview the Item
- Select more than maxChoices value
**Actual result:** User is able to select the value greater than maximum 
**Expected result:** “Maximum number of choices reached.“ message is displayed to the user. User is not able to select more than maximum set in constraints
> fix/AUT-2713 Choice interaction - Incorrect amount of choices are allowed to be selected if maxChoices = minChoices

- src/qtiCommonRenderer/helpers/Graphic.js
Related to: https://oat-sa.atlassian.net/browse/AUT-1910
**!Will be separate ticket to rework responsive and fixed sizes for graphic interactions**
Issue: 
1. when size of background image for HotSpot updated - coords of shapes wasn't recalculated
2. size of image wasn't restored after reopening item in Authoring
How to test:
- go to item Authoring
- add HotSpot interaction
- add shapes on it
- go to item Style Editor, set Item width to Defined width
- set focus on HotSpot interaction
- update size
- save item
- reopen in Item Authoring, see the same size
- open in preview, see that HotSpots on proper positions and size in correct
> fix: scale coords if background resized

- src/qtiItem/helper/xmlNsHandler.js
Related to: https://oat-sa.atlassian.net/browse/AUT-2499
**Issue:** on save `taoQtiItem/views/js/qtiCreator/widgets/item/Widget.js`  renders XML and calls `xmlNsHandler.restoreNs` to restore namespaces. `figure` will be converted to `qh5:figure`. Is is ok for XML, but markup inside PCI - just HTML, and validated on BE as HTML. So `qh5:figure` in `markup` fails
**Solution:** do not set namespaces on what is inside `markup`
How to check:
1. Create a new item with a MathEntry PCI
2. Add an image to its prompt
3. Save it and go back to Items
4. Edit the same Item again
5. Save the item without modify anything
> fix: flag don't add prefix in markup

- src/qtiCommonRenderer/renderers/interactions/AssociateInteraction.js
**Related to:**
https://oat-sa.atlassian.net/browse/AUT-2716
**STEPS TO TEST:**
1. Create an item with a common associate interaction
2. Add photo, audio and video elements.
3. Go to preview and create pairs
**CURRENT RESULT:**
- When adding a video or audio file in second element pair, error shows in console and new pair gaps don't show.
**EXPECTED RESULT:**
- When adding a pair no matter what content is present in choice, no errors show in console and new pair gap is present 
- Response scores in delivery and preview work as expected.
> Fix/aut 2716/association interaction not able to add pairs after mediaplayer

- src/qtiCommonRenderer/renderers/Figure.js
- src/qtiCommonRenderer/tpl/figure.tpl
Related to: https://oat-sa.atlassian.net/browse/AUT-2673
Issue with edit old inline figure. On customer env serial doesn't contain `figure_` in serial, then was added `data-figure="true"` flag. Also no need to move width in case parent is not `figure` (`span` in case it is inline).
> fix: support old inline figure

- package-lock.json
- package.json
- src/qtiCommonRenderer/renderers/Figure.js
- src/qtiCommonRenderer/tpl/figure.tpl
Related to: https://oat-sa.atlassian.net/browse/AUT-2673
Backport of https://github.com/oat-sa/tao-item-runner-qti-fe/pull/341 to [November release](https://github.com/oat-sa/tao-community/blob/2022.11.4/composer.json#L39) [taoQtiITem v29.14.4.4](https://github.com/oat-sa/extension-tao-itemqti/blob/v29.14.4.4/views/package.json#L12)
> Hotfix/aut 2673/support old inline figure to November release

- src/qtiCommonRenderer/helpers/Graphic.js
- src/qtiCommonRenderer/renderers/interactions/GraphicAssociateInteraction.js
- src/qtiCommonRenderer/renderers/interactions/GraphicGapMatchInteraction.js
- src/qtiCommonRenderer/renderers/interactions/GraphicOrderInteraction.js
- src/qtiCommonRenderer/renderers/interactions/HotspotInteraction.js
- src/qtiCommonRenderer/renderers/interactions/SelectPointInteraction.js
Related to: https://oat-sa.atlassian.net/browse/AUT-2869
Regression after https://oat-sa.atlassian.net/browse/AUT-1910
**Fix:** use property `responsive` in Graphic helper, see https://github.com/oat-sa/tao-item-runner-qti-fe/pull/351/commits/dd690ffa74185a0ba289bc7d03b3f94eb766a06e
- Click the "Items" tab, create a new Item and click its "Authoring" button
- Drag and drop any Graphic Interactions on the canvas
- Click Save and Preview
**Actual result:**  Background image does not accept canvas size
> fix: responsive mode for background in graphic interactions

- src/qtiItem/core/Loader.js
This PR aims to fix `inlineChoice`'s compatibility with its older data format relying on `text` attribute while keeping the new implementation relying on the `body` element.
https://user-images.githubusercontent.com/2943256/221191076-4bea3b63-1c02-4e7f-ad43-620dc5e4a284.mov
[OATSD-2361]: https://oat-sa.atlassian.net/browse/OATSD-2361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: compatibility with `text`-based inline choice options

- src/qtiCommonRenderer/renderers/interactions/AssociateInteraction.js
coming from [https://oat-sa.atlassian.net/browse/AUT-3027](https://oat-sa.atlassian.net/browse/AUT-3027)
changelog:
* change drop options to enable drop area when mouse is on over while dragging
> fix: updates overlap options

- src/qtiCommonRenderer/renderers/interactions/AssociateInteraction.js
Ticket: https://oat-sa.atlassian.net/browse/AUT-2716
- What's Changed
Check for choice object before get its ID to avoid null access.
- How to test (took from ticket)
1. Go to Items tab
2. Choose an item from Preconditions and click ‘Preview’
3. Drag and drop 1 choice containing the media and one without it into the empty association pair
Actual result: Pair is created but user cannot create more pairs, empty pair doesn’t appear. Several errors appear in browser console, the last dragged choice is stuck with mouse cursor.
Expected result: Association pair is added, empty pair appears so it is possible to create a new association pair. No errors in DevTools console.
> feature: check for interaction choice validity before add its id

- src/qtiCommonRenderer/renderers/interactions/ChoiceInteraction.js
This PR addresses an issue of losing the item-level styles of certain parts of a choice interaction upon resetting the invalid-response state.
⚠️ The fix is far from being perfect as obviously a better option would be to introduce proper validation-error-state CSS classes, but will do for the time being.
|Before|After|
|-|-|
|<img width="928" alt="image" src="https://user-images.githubusercontent.com/2943256/233975052-5ebf44a3-924b-4cd7-8b32-080fee7816c5.png">|<img width="928" alt="image" src="https://user-images.githubusercontent.com/2943256/233974970-dff7f4ab-8e83-4bdb-8f40-21fb7107f140.png">|
1. Have an item with a horizontal layout choice interaction
2. Have some images with static size as choice options
3. Have a max-choice validation applied
4. Select more than allowed choices
The …
> Fix TR-5398 unwanted style removal on choice interaction validation

- src/qtiCommonRenderer/renderers/Figure.js
- src/qtiCommonRenderer/tpl/figure.tpl
related to https://oat-sa.atlassian.net/browse/BSA-370
Rollback of changes introduced for May release by https://oat-sa.atlassian.net/browse/AUT-2673
Check description of the ticket and check display of item is back to desired by customer
Kitchen env is referred in the Environment field of the ticket
> hotfix/bsa 370/rollback inline img

- src/qtiItem/helper/maxScore.js
- test/qtiItem/maxScore/data/external-scored-none.json
- test/qtiItem/maxScore/data/external-scored.json
- test/qtiItem/maxScore/test.js
Tickets: 
- https://oat-sa.atlassian.net/browse/AUT-3353
- https://oat-sa.atlassian.net/browse/AUT-3354
- `MAXSCORE` value has been set to the `SCORE` upper bound value in case it is configured with `externalScored` set to `Human` or `External Machine`.
- In case defined `SCORE` the custom `Outcome Declarations` values are ignored.
- Authoring UI deletes the SCORE and MAXSCORE outcome variables when all interactions are configured with none response processing rule, and the externalScored property of the SCORE variable is set to None
- Create a test item with some interactions
- Switch `Response processing` to none
- Set up `Outcome Declarations` `SCORE` option and choose the value's range
- Save the item
- Go to item preview
- Submit the test
- The `MAXSCORE` should be equal to the upper …
> feat: update MAXSCORE with external SCORE value

- src/qtiItem/core/interactions/EndAttemptInteraction.js
- src/qtiItem/core/interactions/UploadInteraction.js
- test/qtiItem/maxScore/test.js
Tickets:
https://oat-sa.atlassian.net/browse/AUT-2604,
https://oat-sa.atlassian.net/browse/AUT-3593
- Exposed normal maximum as zero for the EndAttemptInteraction and UploadInteraction
- It will be considered during maxscore calculation for the test item 
and prevent removing the maxscore outcome variable from the item
- Create a new item
- DnD a Choice Interaction
- Save the item
- DnD “End attempt“ Interaction
- Save the Item 
- Preview the Item and click "Submit"
- Check both the MAXSCORE and SCORE outcomes are present
- Repeat this flow with "File Upload" interaction
**Available for test on**: http://test-viktar-2.playground.kitchen.it.taocloud.org:42481/
> fix: expose zero maxscore for upload and endAttempt interactions

- src/qtiCommonRenderer/renderers/interactions/TextEntryInteraction.js
Related to: https://oat-sa.atlassian.net/browse/TR-6116
When the Text Entry input field is blurred:
A red border to the input is displayed.
A tooltip is displayed above the input, mentioning the accepted number format for the input (adapted for configured decimalSeparator and thousandsSeparator), for example Invalid value, use . (dot) for decimal point and , (comma) for thousands separator.
The value is still truncated if submitted as an invalid value.
> feat: Add tooltip for wrong decimal format in Text Entry

- src/qtiCommonRenderer/renderers/interactions/TextEntryInteraction.js
Related to: https://oat-sa.atlassian.net/browse/TR-6116
After implementing decimal validation, in cases of incorrect format, no value was sent. The 'invalid' class on the input prevented data from being taken from the input, which caused the errors. Removing the 'invalid' class and leaving the 'error' class for correct CSS styling was the solution for this bug.
https://github.com/oat-sa/tao-item-runner-qti-fe/assets/133767102/d5dfbea0-ac53-4d8c-af04-d13c3b1db25e
> fix: send decimal value if is wrong format

- src/qtiItem/core/Container.js
Ticket: [AUT-3670](https://oat-sa.atlassian.net/browse/AUT-3670)
- Fixed the saving of item interaction when it have curly braces around placeholder
http://test-kiril.playground.kitchen.it.taocloud.org:40351/tao/Main/login
admin/admin
[AUT-3670]: https://oat-sa.atlassian.net/browse/AUT-3670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AUT-3670] fix: removing hb special symbols around placeholder

- src/qtiItem/helper/maxScore.js
- test/qtiItem/maxScore/data/external-scored-outcome.json
- test/qtiItem/maxScore/test.js
Ticket: https://oat-sa.atlassian.net/browse/AUT-3693
- Fixed rules for Deleting `SCORE` and `MAX_SCORE` and applying Default `SCORE` Value
- The `SCORE` and `MAX_SCORE` will be deleted when response processing is none and all other outcomes marked with `External scored` = `none`
-  The `SCORE` and `MAX_SCORE` will NOT be deleted when response processing is none and at least one outcome marked with `External scored` with `Human` or `External machine`
- The default value `0` will be applied for `SCORE` outcome for the case described just above
- Create a test and check the cases described in `What's Changed` section.
The changes applied in scope of https://github.com/oat-sa/extension-tao-itemqti/pull/2524
**Deployed** to http://test-viktar.playground.kitchen.it.taocloud.org:41531/tao/Main/lo …
> fix: rules for deleting SCORE and MAXSCORE outcomes

- src/qtiItem/helper/maxScore.js
- test/qtiItem/maxScore/data/no-responses.json
- test/qtiItem/maxScore/test.js
Ticket: https://oat-sa.atlassian.net/browse/AUT-3735
Fixed the issue when after deleting of an interaction which was contained responses and custom outcome declarations, they will be not deleted properly and will generate inconsistency inside XML
- Custom outcome declarations are deleted if there are no responses in the item
- Create an item with choice interaction, for example, and create a Human response declaration and save it
- Put in the item some shared stimulus with a file and delete the previously added choice interaction and press save
- All outcome declarations should be deleted if no more interactions with responses
Appropriate PR in consumer: https://github.com/oat-sa/extension-tao-itemqti/pull/2549
**Deployed** to https://construct1-oat-unit07.dev.gcp-eu.taocloud.org/tao/Main/ …
> fix: remove custom outcomes if no responses in the item

- src/qtiCommonRenderer/renderers/interactions/OrderInteraction.js
- src/qtiCommonRenderer/tpl/interactions/orderInteraction.tpl
Ticket: https://oat-sa.atlassian.net/browse/AUT-3715
- Added support of new options by order interaction (`single` and `sort` order)
- Create an item containing order interactions with `single` and/or `sort` order options
- Check different states, switching between views with different settings
PR in consumer: https://github.com/oat-sa/extension-tao-itemqti/pull/2532
The changes are deployed to [unit-06 construct](https://construct1-oat-unit06.dev.gcp-eu.taocloud.org/tao/Main/login)
> feat: single order interaction

- src/qtiCommonRenderer/renderers/interactions/OrderInteraction.js
- src/qtiCommonRenderer/tpl/interactions/orderInteraction.tpl
[Ticket](https://oat-sa.atlassian.net/browse/AUT-3940)
Before:
Now:
How to test:
Create item with single order interaction, check data-order attr by save or import.
Related PRs: [#2617](https://github.com/oat-sa/extension-tao-itemqti/pull/2617), [#1329](https://github.com/oat-sa/tao-deliver-fe/pull/1329)
> [AUT-3940] Fix: Single order interaction, moving from order to data-order.

- src/qtiItem/helper/maxScore.js
- test/qtiItem/maxScore/test.js
We allow to set 0 upperBound in response map or disable upperBound at all, the issue was that we did not separate max score outcome value calculation logic for that two cases and treated 0 as disabled upperBound
This is follow up change
[AUT-4062](https://oat-sa.atlassian.net/browse/AUT-4062)
[AUT-4062]: https://oat-sa.atlassian.net/browse/AUT-4062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: cut maxscore to a zero response upper bound if is's set

- src/qtiCommonRenderer/renderers/interactions/TextEntryInteraction.js
Related to https://oat-sa.atlassian.net/browse/TR-6450
`writing-mode: vertical-rl` for TextEntryInteraction.
- Safari < 17.4 support (where `<input>` will be rendered horizontally) moved to separate ticket: https://oat-sa.atlassian.net/browse/TR-6480
- `maxlength` behavior fully relies on native `input` attribute. [_I don't remember if it works in Safari with autocomplete composition; maybe only in newest versions of Safari]_. There were no related customer bugs about _Terre,_ so didn't make any changes.
see ticket comment
- base item layout: see list here: https://github.com/oat-sa/extension-tao-itemqti/pull/2669
- inline choice interaction: see list here: https://github.com/oat-sa/extension-tao-itemqti/pull/2671
- text entry interaction		
- …
> Feature/tr 6450/vertical textentry

- src/qtiCommonRenderer/renderers/interactions/InlineChoiceInteraction.js
Related to https://oat-sa.atlassian.net/browse/TR-6448
`writing-mode: vertical-rl` for InlineChoiceInteraction.
- base item layout: see list here: https://github.com/oat-sa/extension-tao-itemqti/pull/2669
- inline choice interaction		
- https://github.com/oat-sa/tao-core-libs-fe/pull/117
- https://github.com/oat-sa/tao-item-runner-qti-fe/pull/419
- https://github.com/oat-sa/extension-tao-itemqti/pull/2671
- https://github.com/oat-sa/tao-core-ui-fe/pull/630
- https://github.com/oat-sa/tao-core/pull/4195
> Feature/tr 6448/vertical inlinechoice

- src/qtiCommonRenderer/renderers/interactions/MediaInteraction.js
Just encountered a bug when testing media in CG. It happens in a resize handler, testing if a Number value `.includes('%')`.
> Fix: MediaInteraction cast currentWidth to string before testing for %

- src/qtiCommonRenderer/renderers/interactions/ChoiceInteraction.js
Related to: [INF-209](https://oat-sa.atlassian.net/browse/INF-209)
Previously, the maxChoices validation was only enforced during mouse selection but was being bypassed when choices were selected using keyboard navigation (space key). This fix adds the same validation checks to keyboard selection when an input event is triggered via keyboard, ensuring consistent behavior across both mouse and keyboard interactions.
https://github.com/user-attachments/assets/2c96b8cb-d6f7-4a7a-b7c9-74c4cbe2fb62
[INF-209]: https://oat-sa.atlassian.net/browse/INF-209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Enforce validation during keyboard selection

- package-lock.json
- package.json
**Related to:** https://oat-sa.atlassian.net/browse/AUT-4106
Some mime types have the extension hardcoded in the label. There is no need now that the extension has been added to the list
**Changes:**
- Link to the FE package with the change https://github.com/oat-sa/tao-core-sdk-fe/pull/194
**How to check:**
- Code available to check in [unit13](https://tenant01-oat-unit13.dev.gcp-eu.taocloud.org/login)
- Check in the companion PR https://github.com/oat-sa/extension-tao-itemqti/pull/2690
> chore: add link to package changed

- src/qtiCommonRenderer/helpers/Graphic.js
- src/qtiCommonRenderer/renderers/interactions/SelectPointInteraction.js
https://oat-sa.atlassian.net/browse/AUT-4134
Select Point fix, broken switch between Q&A modes
- Open an item in Authoring mode
- Drag and drop Select Point interaction on the canvas
- Click 'Response' button
- Drag and drop target on the canvas
- Click 'Question' button
- Click 'Response' button
Broken:
Fixed:
> [AUT-4134] Fix: for trigger empty raphael element events in Select Point interaction

- src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
[INF-285](https://oat-sa.atlassian.net/browse/INF-285)
Fix for non standard input in extended text interaction.
How to reproduce:
- Create item with extended text interaction
- Set constrains to max length
- Run preview
- Try Japanese input 
Before：
After
[INF-285]: https://oat-sa.atlassian.net/browse/INF-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [INF-285] Fix: change for text area value restrictions when input done by not regular tools

- src/qtiCommonRenderer/renderers/interactions/ExtendedTextInteraction.js
Related to https://oat-sa.atlassian.net/browse/INF-333
[Deployed to unit01](https://oat-sa.atlassian.net/browse/TR-6452?focusedCommentId=305524)
Have plain ExtendedText _without_ `maxlength`.
Enter something (normally or using IME composition).
Blur or finish composition.
Text is lost --> because `maxlength: 0`, which passes `maxlength !== null` check
Was broken in https://github.com/oat-sa/tao-item-runner-qti-fe/pull/253 ? Or at that time `patternMask = ""` was true and authoring/compilation changed later?
Not related to [INF-285](https://oat-sa.atlassian.net/browse/INF-285)
Failing unit test was fixed in another PR: https://github.com/oat-sa/tao-item-runner-qti-fe/pull/442/commits/38b8f4ba974249344dd7b0d6ff0a2cbb0730b507
[INF-285]: …
> Fix/INF-333/extendedtext: text was cut to 0 chars if no maxlength

- src/qtiCommonRenderer/tpl/instruction.tpl
Related to https://oat-sa.atlassian.net/browse/TR-6577
Use with https://github.com/oat-sa/extension-tao-itemqti/pull/2755
Deployed to [unit01](https://oat-sa.atlassian.net/browse/TR-6452?focusedCommentId=305524) "_Delivery of jun25 jap numbers_"
Vertical-writing, ChoiceInteraction, maxChoices feedback:
for a moment after load, html markup is shown as a plain text. After a couple of seconds, it's replaced with proper markup.
Solution: in [Instruction.update](https://github.com/oat-sa/tao-item-runner-qti-fe/blob/develop/src/qtiCommonRenderer/helpers/instructions/Instruction.js#L62) `message` is already set as html, so we need to do the same when rendering *.tpl in `Instruction.create`.
> Fix/tr 6577/vertical writing numbers

- src/qtiItem/core/response/SimpleFeedbackRule.js
#https://oat-sa.atlassian.net/browse/TR-5815
fix: add isNull to response feedback rules
Select `is null` in the Response feedback rules
Add `isNull` condition
> fix: add isNull to response feedback rules
